spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/music_auth_db
    username: postgres
    password: verystrongpassword
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  accessExpiration: 3600000
  refreshExpiration: 86400000
  jwtSecret: secretKey

server:
          port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka